### ISSUE TITLE
.Schematic depends on missing libraries

### ISSUE THREAD

**Issue by MrBlinky** [ricaflops/Jupiter-II#9]
opening a schematic reports missing libraries:

rfl_memory.lib
rfl_pld.lib

Request: Export schematic to PDF using plot for easy reference

**Comment by ricaflops** [comment]
extra library and PDF schematic uploaded

**Comment by ricaflops** [comment]
Hi, Mr.Blinky
Library and PDF schematic uploaded.
Thank you!Ricardo

    Em terça-feira, 6 de outubro de 2020 07:36:00 BRT, Mr.Blinky <notifications@github.com> escreveu:  
 
 


opening a schematic reports missing libraries:

rfl_memory.lib
rfl_pld.lib

Request: Export schematic to PDF using plot for easy reference

**Comment by MrBlinky** [comment]
Hi Ricardo,

Thank you for adding the library files and schematics.
